### ISSUE TITLE
intoroduce method to set last visible date.

### ISSUE THREAD

**Issue by devDroidRaul** [badoualy/datepicker-timeline#2]
hi love the library u created from the inspiration of the design. 

There occasion when u don't want the user to pink up the date after a given date, for example not beyond today's date. 

To cover max use cases. can v make the adapter to look if the developer has set last visible date. if not we can have the infinite scrollable date picker as it is right now

**Comment by badoualy** [comment]
It could be done pretty easily, I'll look into it as soon as I have some free time

**Comment by badoualy** [comment]
Hey!
Available with release 1.0.0
Use method `setLastVisibleDate`
See [sample](https://github.com/badoualy/datepicker-timeline/blob/master/sample/src/main/java/com/github/badoualy/datepicker/sample/MainActivity.java#L30) for example :)
