### ISSUE TITLE
StringIndexOutOfBoundsException on MonthView

### ISSUE THREAD

**Issue by MrHadiSatrio** [badoualy/datepicker-timeline#20]
Recently, my app has reported a significant number of crashes that was caused by `StringIndexOutOfBoundsException` from within this library's `MonthView`.

The crash logs have led me here:
```
String text = MONTHS[month].substring(0, 3).toUpperCase(Locale.US);
```

It's an early guess, but it seems like there is a possibility for `MONTHS[month]` to be less than 3 in length. Hence the error.

**Comment by badoualy** [comment]
Dupe of #12 
I'll try to fix ASAP, feel free to make a PR if you have the time

**Comment by MrHadiSatrio** [comment]
Oops, sorry, had no idea. I didn't suspect it has relation to the activity lifecycle / restore mechanism.

I'll try to come up with something. In the mean time, could you please review my existing PR #18? Thanks!

**Comment by badoualy** [comment]
It doesn't, just the same bug :)

Will check
