### ISSUE TITLE
Months and Timeline dont center properly

### ISSUE THREAD

**Issue by devDroidRaul** [badoualy/datepicker-timeline#4]
For Release 1.0.0
When selecting date on timelineview or month monthview, selected month doesn't centre on the month view. Same issue when scrolling timelineview, the month view starts to scroll, but the current selected month is not visible. 

Understanding is that, if the selected date is visible on the timelineview, and we start to scroll left or right on the timeline the month view will also scroll in the same direction.

**Comment by badoualy** [comment]
Release 1.0.1 is doing just that, I thought it was already the case in v1.0.0.

You can also disable the feature via setFollowScroll method.

**Comment by badoualy** [comment]
Ok, I think I found the bug you're talking about, it happens when setFirstVisibleDate is set, currently looking into it

**Comment by badoualy** [comment]
Fixed with 63fcb14
Not releasing yet, still having a small bug with the positioning when following scroll, the offset is a bit off, I'll open a new issue.
